### ISSUE TITLE
[TLS Auth] Go based remediation components

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec-docs#583]
As per https://github.com/crowdsecurity/cs-firewall-bouncer/issues/371#issue-2362988545 we  should update all go based remediation components documentation that TLS authentication can be used

All Go based remediation support the following yaml as long as they are using our `go-cs-bouncer` library which most/all are:

```yaml
cert_path: /path/to/file
key_path: /path/to/file
ca_cert_path: /path/to/file
```
